import React, { useState } from 'react';

function App() {
  // State variables for filters and vehicle data
  const [make, setMake] = useState('');
  const [model, setModel] = useState('');
  const [distance, setDistance] = useState('');
  const [zipCode, setZipCode] = useState('');
  const [vehicles, setVehicles] = useState([]);

  // Function to handle search based on filters
  const handleSearch = () => {
    // Your logic to fetch filtered vehicles from the backend
    // Update the vehicles state with the filtered data received from the backend
  };
// Popular Makes 
const allMakes = [
  "All makes",
  "Acura",
  "Audi",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Dodge",
  "Ford",
  "Genesis",
  "GMC",
  "Honda",
  "Hyundai",
  "INFINITI",
  "Jaguar",
  "Jeep",
  "Kia",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Mazda",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "RAM",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
  "AC",
  "Alfa Romeo",
  "Am General",
  "American Motors",
  "Aston Martin",
  "Austin-Healey",
  "Avanti Motors",
  "Bentley",
  "Bricklin",
  "Bugatti",
  "Daewoo",
  "Datsun",
  "Delorean",
  "Desoto",
  "DeTomaso",
  "Edsel",
  "Facel-Vega",
  "Ferrari",
  "FIAT",
  "Fisker",
  "Geo",
  "Hudson",
  "Hummer",
  "INEOS",
  "International",
  "Isuzu",
  "Jensen",
  "Kaiser",
  "Karma",
  "Koenigsegg",
  "Lamborghini",
  "Lancia",
  "LaSalle",
  "Lotus",
  "Lucid",
  "Maserati",
  "Maybach",
  "McLaren",
  "Mercury",
  "MG",
  "Morgan",
  "Nash",
  "Oldsmobile",
  "Opel",
  "Packard",
  "Pagani",
  "Panoz",
  "Plymouth",
  "Polestar",
  "Pontiac",
  "Renault",
  "Rivian",
  "Rolls-Royce",
  "Rover",
  "Saab",
  "Saturn",
  "Scion",
  "smart",
  "Spyker",
  "Studebaker",
  "Sunbeam",
  "Suzuki",
  "Triumph",
  "Willys",
];

   // Models for Acura
   const acuraModels = [
    "All models",
    "CL",
    "ILX",
    "ILX Hybrid",
    "Integra",
    "Legend",
    "MDX",
    "MDX Sport Hybrid",
    "NSX",
    "RDX",
    "RL",
    "RLX",
    "RLX Sport Hybrid",
    "RSX",
    "TL",
    "TLX",
    "TSX",
    "Vigor",
    "ZDX",
  ];

  // Models for Audi
  const audiModels = [
    "All models",
    "100",
    "200",
    "A3",
    "A3 e-tron",
    "A4",
    "A4 allroad",
    "A5",
    "A5 Sportback",
    "A6",
    "A6 allroad",
    "A7",
    "A7 e",
    "A8",
    "A8 e",
    "allroad",
    "Cabriolet",
    "e-tron",
    "e-tron GT",
    "e-tron S",
    "e-tron Sportback",
    "GT",
    "Q3",
    "Q4 e-tron",
    "Q4 e-tron Sportback",
    "Q5",
    "Q5 e",
    "Q5 hybrid",
    "Q5 Sportback",
    "Q7",
    "Q8",
    "Q8 e-tron",
    "Q8 e-tron Sportback",
    "R8",
    "RS 3",
    "RS 4",
    "RS 5",
    "RS 6 Avant",
    "RS 7",
    "RS e-tron GT",
    "RS Q8",
    "RS6",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "SQ5",
    "SQ5 Sportback",
    "SQ7",
    "SQ8",
    "SQ8 e-tron",
    "SQ8 e-tron Sportback",
    "TT",
    "TT RS",
    "TTS",
  ];

  // Models for BMW
  const bmwModels = [
    "All models",
    "1-Series",
    "  128",
    "  135",
    "1500",
    "1600",
    "1800",
    "2-Series",
    "  228",
    "  228 Gran Coupe",
    "  230",
    "2000",
    "2002",
    "2500",
    "2600",
    "3-Series",
    "  320",
    "  323",
    "  325",
    "  328",
    "  328 Gran Turismo",
    "  328d",
    "  330",
    "  330 Gran Turismo",
    "  330e",
    "  335",
    "  335 Gran Turismo",
    "  340",
    "  340 Gran Turismo",
    "4-Series",
    "  428",
    "  428 Gran Coupe",
    "  430",
    "  430 Gran Coupe",
    "  435",
    "  435 Gran Coupe",
    "  440",
    "  440 Gran Coupe",
    "5-Series",
    "  525",
    "  528",
    "  530",
    "  530e",
    "  535",
    "  535 Gran Turismo",
    "  535d",
    "  540",
    "  550",
    "  550 Gran Turismo",
    "6-Series",
    "  600",
    "  640",
    "  640 Gran Coupe",
    "  640 Gran Turismo",
    "  645",
    "  650",
    "  650 Gran Coupe",
    "  ALPINA B6 Gran Coupe",
    "7-Series",
    "  740",
    "  740e",
    "  745",
    "  745e",
    "  750",
    "  750e",
    "  760",
    "  ALPINA B7",
    "8-Series",
    "  840",
    "  840 Gran Coupe",
    "  850",
    "  ALPINA B8 Gran Coupe",
    "i-Series",
    "  i3",
    "  i4 Gran Coupe",
    "  i7",
    "  i8",
    "  iX",
    "i5",
    "M-Series",
    "  M",
    "  M2",
    "  M235",
    "  M235 Gran Coupe",
    "  M240",
    "  M3",
    "  M340",
    "  M4",
    "  M440",
    "  M440 Gran Coupe",
    "  M5",
    "  M550",
    "  M6",
    "  M6 Gran Coupe",
    "  M760",
    "  M8",
    "  M8 Gran Coupe",
    "  M850",
    "  M850 Gran Coupe",
    "X-Series",
    "  ALPINA XB7",
    "  X1",
    "  X2",
    "  X3",
    "  X3 M",
    "  X3 PHEV",
    "  X4",
    "  X4 M",
    "  X5",
    "  X5 M",
    "  X5 PHEV",
    "  X5 eDrive",
    "  X6",
    "  X6 M",
    "  X7",
    "  XM",
    "Z3",
    "Z4",
    "Z8",
  ];

  // Models for Buick
  const buickModels = [
    "All models",
    "California",
    "Cascada",
    "Century",
    "Electra",
    "Enclave",
    "Encore",
    "Encore GX",
    "Envision",
    "Envista",
    "GranSport",
    "GS 350",
    "GS 400",
    "GS 455",
    "LaCrosse",
    "LeSabre",
    "Limited",
    "Lucerne",
    "Master",
    "Model 40",
    "Model B",
    "Model H",
    "Model S",
    "Park Avenue",
    "Rainier",
    "Reatta",
    "Regal",
    "Regal Sportback",
    "Regal TourX",
    "Rendezvous",
    "Riviera",
    "Roadmaster",
    "Series 60",
    "Skylark",
    "Special",
    "Standard",
    "Super",
    "Terraza",
    "Verano",
    "Wildcat",
  ];

    // Models for Cadillac
    const cadillacModels = [
      "All models",
      "Allante",
      "ATS",
      "ATS-V",
      "Brougham",
      "Calais",
      "Catera",
      "CT4",
      "CT4-V",
      "CT5",
      "CT5-V",
      "CT6",
      "CT6 PLUG-IN",
      "CT6-V",
      "CTS",
      "CTS-V",
      "Custom",
      "DeVille",
      "DTS",
      "Eldorado",
      "ELR",
      "Escalade",
      "Escalade ESV",
      "Escalade EXT",
      "Escalade Hybrid",
      "Fleetwood",
      "LYRIQ",
      "Model A",
      "Model B",
      "Model H",
      "Model S",
      "Model T",
      "Series 60",
      "Series 61",
      "Series 62",
      "Series 70",
      "Seville",
      "SRX",
      "STS",
      "Type 57",
      "V-16",
      "XLR",
      "XT4",
      "XT5",
      "XT6",
      "XTS",
    ];
  
  // Models for Chevrolet
  const chevroletModels = [
    "All models",
    "150",
    "1500",
    "210",
    "2500",
    "3100",
    "3500",
    "Apache",
    "Astro",
    "Avalanche",
    "Aveo",
    "Bel Air",
    "Beretta",
    "Biscayne",
    "Blazer",
    "Blazer EV",
    "Bolt EUV",
    "Bolt EV",
    "Brookwood",
    "C10/K10",
    "C20/K20",
    "Camaro",
    "Cameo Carrier",
    "Caprice",
    "Caprice Classic",
    "Caprice Police Patrol Vehicle",
    "Captiva Sport",
    "Cavalier",
    "Chevelle",
    "Chevy II",
    "City Express",
    "Classic",
    "Cobalt",
    "Colorado",
    "Confederate",
    "Corvair",
    "Corvette",
    "Corvette E-Ray",
    "Corvette Stingray",
    "Cruze",
    "Cruze Limited",
    "Delray",
    "Deluxe",
    "El Camino",
    "Equinox",
    "Equinox EV",
    "Express Vans",
    "Fleetline",
    "Fleetmaster",
    "HHR",
    "Impala",
    "Impala Limited",
    "Independence",
    "Lumina",
    "Malibu",
    "Malibu Classic",
    "Malibu Hybrid",
    "Malibu Limited",
    "Malibu Maxx",
    "Master",
    "Master 85",
    "Master Deluxe",
    "Metro",
    "Monte Carlo",
    "Nomad",
    "Nova",
    "Panel",
    "Pickup Truck",
    "Prizm",
    "S-10",
    "S-10 Blazer",
    "Sedan Delivery",
    "Silverado Trucks",
    "Sonic",
    "Spark",
    "Spark EV",
    "Special Deluxe",
    "Sportvan",
    "Sprint",
    "SS",
    "SSR",
    "Standard",
    "Styleline",
    "Stylemaster",
    "Suburban",
    "Tahoe",
    "Tahoe Hybrid",
    "Tracker",
    "Trailblazer",
    "TrailBlazer EXT",
    "Traverse",
    "Traverse Limited",
    "Trax",
    "Uplander",
    "Vega",
    "Venture",
    "Volt",
  ];

   // Models for Chrysler
   const chryslerModels = [
    "All models",
    "200",
    "300",
    "300C",
    "300M",
    "Aspen",
    "Aspen Hybrid",
    "Cirrus",
    "Concorde",
    "Cordoba",
    "Crossfire",
    "E Class",
    "Grand Voyager",
    "Laser",
    "LeBaron",
    "LHS",
    "New Yorker",
    "Pacifica",
    "Pacifica Hybrid",
    "Prowler",
    "PT Cruiser",
    "Sebring",
    "TC by Maserati",
    "Town & Country",
    "Voyager",
  ];

   // Models for Dodge
   const dodgeModels = [
    "All models",
    "330",
    "440",
    "600",
    "880",
    "Aspen",
    "Avenger",
    "Caliber",
    "Caravan",
    "Challenger",
    "Charger",
    "Coronet",
    "Custom",
    "D100",
    "D150",
    "D250",
    "D350",
    "Dakota",
    "Dart",
    "Deluxe",
    "Durango",
    "Grand Caravan",
    "Hornet",
    "Intrepid",
    "Journey",
    "Lancer",
    "Magnum",
    "Matador",
    "Meadowbrook",
    "Monaco",
    "Neon",
    "Nitro",
    "Panel",
    "Polara",
    "Power Wagon",
    "Raider",
    "Ram Trucks",
    "Ram Van",
    "Ram Wagon",
    "Ramcharger",
    "Shadow",
    "Special",
    "Sprinter",
    "SRT Viper",
    "Standard",
    "Stealth",
    "Stratus",
    "Suburban",
    "Super Bee",
    "Van",
    "Viper",
    "W250",
  ];
  // Models for Ford
  const fordModels = [
    "All models",
    "Bronco",
    "Bronco II",
    "Bronco Sport",
    "C-Max Energi",
    "C-Max Hybrid",
    "Club Sedan",
    "Club Wagon",
    "Contour",
    "Country Squire",
    "Coupe",
    "Crestline",
    "Crown Victoria",
    "Custom",
    "Customline",
    "Deluxe",
    "E-Transit",
    "Econoline Vans",
    "EcoSport",
    "Edge",
    "Elite",
    "Escape",
    "Escape Hybrid",
    "Escape PHEV",
    "Escort",
    "Excursion",
    "Expedition (all)",
    "Explorer",
    "Explorer Sport",
    "Explorer Sport Trac",
    "F-Series Trucks",
    "Fairlane",
    "Fairlane 500",
    "Falcon",
    "Fiesta",
    "Five Hundred",
    "Flex",
    "Focus",
    "Focus Electric",
    "Focus RS",
    "Focus ST",
    "Freestar",
    "Freestyle",
    "Fusion",
    "Fusion Energi",
    "Fusion Hybrid",
    "Galaxie",
    "Galaxie 500",
    "Galaxie 500 XL",
    "Gran Torino",
    "GT",
    "GT40",
    "LTD",
    "Mainline",
    "Maverick",
    "Model 18",
    "Model 40",
    "Model 68",
    "Model 78",
    "Model A",
    "Model B",
    "Model R",
    "Model S",
    "Model T",
    "Mustang",
    "Mustang Mach-E",
    "Mustang Shelby GT",
    "Panel",
    "Pickup Truck",
    "Probe",
    "Ranchero",
    "Ranger",
    "Roadster",
    "Sedan Delivery",
    "Sedan Police Interceptor",
    "Shelby GT350",
    "Shelby GT350R",
    "Shelby GT500",
    "Sunliner",
    "Super Deluxe",
    "Taurus",
    "Taurus X",
    "Thunderbird",
    "Torino",
    "Transit Connect",
    "Transit-150",
    "Transit-250",
    "Transit-350",
    "Utility Police Interceptor",
    "Windstar",
    "XL",
  ];

  // Models for Genesis
  const genesisModels = [
    "All models",
    "Electrified G80",
    "Electrified GV70",
    "G70",
    "G80",
    "G90",
    "GV60",
    "GV70",
    "GV80",
  ];
  
  // Models for GMC
  const gmcModels = [
    "All models",
    "1500",
    "2500",
    "3500",
    "Acadia",
    "Acadia Limited",
    "Caballero",
    "Canyon",
    "Envoy",
    "Envoy XL",
    "Envoy XUV",
    "HUMMER EV",
    "HUMMER EV SUV",
    "Jimmy",
    "Panel",
    "Safari",
    "Savana Vans",
    "Savana 1500",
    "Savana 2500",
    "Savana 3500",
    "Sierra Trucks",
    "Pickup Truck",
    "Sierra 1500",
    "Sierra 1500 Hybrid",
    "Sierra 1500 Limited",
    "Sierra 2500",
    "Sierra 3500",
    "Sonoma",
    "Sprint",
    "Suburban",
    "Terrain",
    "Van",
    "Vandura",
    "Yukon",
    "Yukon Hybrid",
    "Yukon XL",
  ];

  //Models for Honda 
  const hondaModels = [
    "All models",
    "600",
    "Accord",
    "Accord Crosstour",
    "Accord Hybrid",
    "Accord Plug-In Hybrid",
    "Civic",
    "Civic Hybrid",
    "Civic Si",
    "Civic Type R",
    "Clarity Plug-In Hybrid",
    "CR-V",
    "CR-V Hybrid",
    "CR-Z",
    "Crosstour",
    "CRX",
    "del Sol",
    "Element",
    "Fit",
    "HR-V",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Prelude",
    "Prologue",
    "Ridgeline",
    "S2000",
  ];
  
  // Model for Hyundai
  const hyundaiModels = [
    "All models",
    "Accent",
    "Azera",
    "Elantra",
    "Elantra GT",
    "Elantra HEV",
    "Elantra N",
    "Elantra Touring",
    "Entourage",
    "Equus",
    "Genesis",
    "Genesis Coupe",
    "IONIQ 5",
    "IONIQ 6",
    "IONIQ EV",
    "IONIQ Hybrid",
    "IONIQ Plug-In Hybrid",
    "Kona",
    "Kona EV",
    "Kona N",
    "NEXO",
    "Palisade",
    "Santa Cruz",
    "Santa Fe",
    "Santa Fe HEV",
    "Santa Fe Plug-In Hybrid",
    "Santa Fe Sport",
    "Santa Fe XL",
    "Sonata",
    "Sonata Hybrid",
    "Sonata Plug-In Hybrid",
    "Tiburon",
    "Tucson",
    "Tucson Hybrid",
    "Tucson Plug-In Hybrid",
    "Veloster",
    "Veloster N",
    "Venue",
    "Veracruz",
    "XG350",
  ];
  
  // Models for INFINITI
  const infinitiModels = [
    "All models",
    "EX35",
    "EX37",
    "FX (all)",
    "  FX35",
    "  FX37",
    "  FX45",
    "  FX50",
    "G (all)",
    "  G20",
    "  G25",
    "  G25x",
    "  G35",
    "  G35x",
    "  G37",
    "  G37x",
    "I (all)",
    "  I30",
    "  I35",
    "IPL G",
    "J30",
    "JX35",
    "M (all)",
    "  M35",
    "  M35h",
    "  M35x",
    "  M37",
    "  M37x",
    "  M45",
    "  M45x",
    "  M56",
    "  M56x",
    "Q40",
    "Q45",
    "Q50",
    "Q50 Hybrid",
    "Q60",
    "Q60 IPL",
    "Q70",
    "Q70h",
    "Q70L",
    "QX (all)",
    "  QX30",
    "  QX4",
    "  QX50",
    "  QX55",
    "  QX56",
    "  QX60",
    "  QX60 Hybrid",
    "  QX70",
    "  QX80",
  ];

  // Models of Jaguar
  const jaguarModels = [
    "All models",
    "340",
    "420",
    "E-PACE",
    "E-Type",
    "F-PACE",
    "F-TYPE",
    "I-PACE",
    "Mark II",
    "Mark IV",
    "Mark IX",
    "Mark V",
    "Mark VII",
    "Mark VIII",
    "S-Type",
    "Vanden Plas",
    "X-Type",
    "XE",
    "XE SV",
    "XF",
    "XJ",
    "XJ12",
    "XJ6",
    "XJ8",
    "XJR",
    "XJR-S",
    "XJS",
    "XK",
    "XK 120",
    "XK 140",
    "XK 150",
    "XK8",
    "XKE",
    "XKR",
  ];
  
  // Models of Jeep
  const jeepModels = [
    "All models",
    "Cherokee",
    "CJ",
    "CJ-5",
    "CJ-7",
    "Comanche",
    "Commander",
    "Commando",
    "Compass",
    "Gladiator",
    "Grand Cherokee",
    "Grand Cherokee 4xe",
    "Grand Cherokee L",
    "Grand Cherokee WK",
    "Grand Wagoneer",
    "Grand Wagoneer L",
    "J10",
    "Jeepster",
    "Liberty",
    "New Compass",
    "Patriot",
    "Renegade",
    "Scrambler",
    "Wagoneer",
    "Wagoneer L",
    "Wrangler",
    "Wrangler 4xe",
    "Wrangler JK",
    "Wrangler JK Unlimited",
    "Wrangler Unlimited",
    "Wrangler Unlimited 4xe",
  ];
  
  // Models of Kia
  const kiaModels = [
    "All models",
    "Amanti",
    "Borrego",
    "Cadenza",
    "Carnival",
    "EV6",
    "EV9",
    "Forte",
    "Forte Koup",
    "K5",
    "K900",
    "Niro",
    "Niro EV",
    "Niro Plug-In Hybrid",
    "Optima",
    "Optima Hybrid",
    "Optima Plug-In Hybrid",
    "Rio",
    "Rio5",
    "Rondo",
    "Sedona",
    "Seltos",
    "Sephia",
    "Sorento",
    "Sorento Hybrid",
    "Sorento Plug-In Hybrid",
    "Soul",
    "Soul EV",
    "Spectra",
    "Spectra5",
    "Sportage",
    "Sportage Hybrid",
    "Sportage Plug-In Hybrid",
    "Stinger",
    "Telluride",
  ];
  
  // Makes of Land Rover
  const landRoverModels = [
    "All models",
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Freelander",
    "LR2",
    "LR3",
    "LR4",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
    "Series II",
    "Series III",
  ];
  
  // Makes of Lexus 
  // Models of Lexus
const lexusModels = [
  "All models",
  "CT 200h",
  "ES (all)",
  "  ES 250",
  "  ES 300",
  "  ES 300h",
  "  ES 330",
  "  ES 350",
  "GS (all)",
  "  GS 200t",
  "  GS 300",
  "  GS 350",
  "  GS 400",
  "  GS 430",
  "  GS 450h",
  "  GS 460",
  "  GS F",
  "GX 460",
  "GX 470",
  "HS 250h",
  "IS (all)",
  "  IS 200t",
  "  IS 250",
  "  IS 250C",
  "  IS 300",
  "  IS 350",
  "  IS 350C",
  "  IS 500",
  "  IS-F",
  "LC 500",
  "LC 500h",
  "LFA",
  "LS (all)",
  "  LS 400",
  "  LS 430",
  "  LS 460",
  "  LS 500",
  "  LS 500h",
  "  LS 600h L",
  "LX (all)",
  "  LX 450",
  "  LX 470",
  "  LX 570",
  "  LX 600",
  "NX 200t",
  "NX 250",
  "NX 300",
  "NX 300h",
  "NX 350",
  "NX 350h",
  "NX 450h+",
  "RC 200t",
  "RC 300",
  "RC 350",
  "RC F",
  "RX (all)",
  "  RX 300",
  "  RX 330",
  "  RX 350",
  "  RX 350L",
  "  RX 350h",
  "  RX 400h",
  "  RX 450h",
  "  RX 450hL",
  "  RX 500h",
  "RX 450h+",
  "RZ 300e",
  "RZ 450e",
  "SC (all)",
  "  SC 300",
  "  SC 400",
  "  SC 430",
  "TX 350",
  "TX 500h",
  "TX 550h+",
  "UX 200",
  "UX 250h",
  "UX 300h"
];

// Makes of Lincoln 
const lincolnModels = [
  "All models",
  "Aviator",
  "Blackwood",
  "Capri",
  "Continental",
  "Corsair",
  "Custom",
  "LS",
  "Mark II",
  "Mark III",
  "Mark IV",
  "Mark LT",
  "Mark V",
  "Mark VI",
  "Mark VII",
  "Mark VIII",
  "MKC",
  "MKS",
  "MKT",
  "MKX",
  "MKZ",
  "MKZ Hybrid",
  "Nautilus",
  "Navigator",
  "Navigator L",
  "Town Car",
  "Zephyr"
];

// Makes of Mazda
const mazdaModels = [
  "All models",
  "1800",
  "323",
  "626",
  "929",
  "B-Series Trucks",
  "  B2300",
  "  B2600",
  "  B3000",
  "  B4000",
  "B2500",
  "CX-3",
  "CX-30",
  "CX-5",
  "CX-50",
  "CX-7",
  "CX-9",
  "CX-90",
  "CX-90 PHEV",
  "Mazda2",
  "Mazda3",
  "Mazda5",
  "Mazda6",
  "MazdaSpeed Miata MX-5",
  "MazdaSpeed Protege",
  "MazdaSpeed3",
  "MazdaSpeed6",
  "Millenia",
  "MPV",
  "MX-30",
  "MX-30 EV",
  "MX-5 Miata",
  "MX-5 Miata RF",
  "MX-6",
  "Pickup Truck",
  "Protege",
  "Protege5",
  "RX-7",
  "RX-8",
  "Tribute"
];

// Makes of Mercedes-Benz
const mercedesModels = [
  "All models",
  "200",
  "230",
  "240",
  "280SE",
  "280SL",
  "300",
  "300C",
  "320",
  "380SL",
  "450SL",
  "600",
  "A-Class",
  "AMG A 35",
  "AMG EQE",
  "AMG EQS",
  "AMG GLB 35",
  "AMG GT",
  "AMG GT 43",
  "AMG GT 53",
  "AMG GT 63",
  "B-Class",
  "B-Class Electric Drive",
  "C (all)",
  "  AMG C",
  "  AMG C 43",
  "  AMG C 63",
  "  C-Class",
  "CL-Class",
  "CLA (all)",
  "  AMG CLA",
  "  AMG CLA 35",
  "  AMG CLA 45",
  "  CLA 250",
  "  CLA-Class",
  "CLK-Class",
  "CLS (all)",
  "  AMG CLS 53",
  "  CLS 450",
  "  CLS 550",
  "  CLS-Class",
  "E (all)",
  "  AMG E 43",
  "  AMG E 53",
  "  AMG E 63",
  "  E-Class",
  "EQB 250",
  "EQB 300",
  "EQB 350",
  "EQE 350",
  "EQE 350+",
  "EQE 500",
  "EQS 450",
  "EQS 450+",
  "EQS 580",
  "eSprinter 2500",
  "G (all)",
  "  AMG G",
  "  AMG G 63",
  "  G 550 4x4 Squared",
  "  G-Class",
  "GL (all)",
  "  GL-Class",
  "GLA (all)",
  "  AMG GLA",
  "  AMG GLA 35",
  "  AMG GLA 45",
  "  GLA 250",
  "  GLA-Class",
  "GLB 250",
  "GLC (all)",
  "  AMG GLC 43",
  "  AMG GLC 63",
  "  GLC 300",
  "  GLC 350e",
  "  GLC-Class",
  "GLE (all)",
  "  AMG GLE",
  "  AMG GLE 43",
  "  AMG GLE 53",
  "  AMG GLE 63",
  "  GLE 350",
  "  GLE 400",
  "  GLE 450",
  "  GLE 550e Plug-In Hybrid",
  "  GLE 580",
  "  GLE-Class",
  "GLE 450 Plug-In Hybrid",
  "GLK-Class",
  "GLS (all)",
  "  AMG GLS 63",
  "  GLS 450",
  "  GLS 550",
  "  GLS 580",
  "  Maybach GLS 600",
  "M-Class",
  "Maybach EQS 680",
  "Maybach S",
  "Maybach S 560",
  "Maybach S 580",
  "Maybach S 650",
  "Maybach S 680",
  "Metris",
  "R-Class",
  "S (all)",
  "  AMG S",
  "  AMG S 63",
  "  AMG S 65",
  "  S-Class",
  "SL (all)",
  "  AMG SL 43",
  "  AMG SL 55",
  "  AMG SL 63",
  "  SL 450",
  "  SL 550",
  "  SL-Class",
  "SLC (all)",
  "  AMG SLC 43",
  "  SLC 300",
  "SLK (all)",
  "  SLK-Class",
  "SLR McLaren",
  "SLS AMG",
  "Sprinter",
  "Sprinter 1500",
  "Sprinter 2500",
  "Sprinter 3500",
  "Sprinter 3500XD",
  "Sprinter 4500"
];

// Makes of MINI
const miniModels = [
  "All models",
  "Clubman",
  "Convertible",
  "Cooper",
  "Cooper Clubman",
  "Cooper Countryman",
  "Cooper S",
  "Cooper S Clubman",
  "Cooper S Countryman",
  "Countryman",
  "Coupe",
  "E Countryman",
  "Hardtop",
  "John Cooper Works GP",
  "Paceman",
  "Roadster",
  "SE Countryman",
  "SE Hardtop"
];

// Makes of Mitsubishi
const mitsubishiModels = [
  "All models",
  "3000GT",
  "Eclipse",
  "Eclipse Cross",
  "Endeavor",
  "Galant",
  "i-MiEV",
  "Lancer",
  "Lancer Evolution",
  "Lancer Sportback",
  "Mirage",
  "Mirage G4",
  "Montero",
  "Montero Sport",
  "Outlander",
  "Outlander PHEV",
  "Outlander Sport",
  "Pickup Truck",
  "Raider"
];

// Makes of Nissan
const nissanModels = [
  "All models",
  "200SX",
  "240SX",
  "280ZX",
  "300ZX",
  "350Z",
  "370Z",
  "Altima",
  "Altima Hybrid",
  "ARIYA",
  "Armada",
  "Cube",
  "Frontier",
  "GT-R",
  "Juke",
  "Kicks",
  "Leaf",
  "Maxima",
  "Murano",
  "Murano CrossCabriolet",
  "Murano Hybrid",
  "NV Vans",
  "  NV Cargo",
  "  NV Cargo NV1500",
  "  NV Cargo NV2500 HD",
  "  NV Cargo NV3500 HD",
  "  NV Passenger",
  "  NV Passenger NV3500 HD",
  "  NV200",
  "NX",
  "Pathfinder",
  "Pathfinder Hybrid",
  "Pickup Truck",
  "Quest",
  "Rogue",
  "Rogue Hybrid",
  "Rogue Select",
  "Rogue Sport",
  "Sentra",
  "Titan",
  "Titan XD",
  "Van",
  "Versa",
  "Versa Note",
  "Xterra",
  "Z"
];

// Makes of Porsche
const porscheModels = [
  "All models",
  "356",
  "718 Boxster",
  "718 Cayman",
  "718 Spyder",
  "911",
  "912",
  "914",
  "924",
  "928",
  "944",
  "968",
  "Boxster",
  "Carrera GT",
  "Cayenne",
  "Cayenne E-Hybrid",
  "Cayenne E-Hybrid Coupe",
  "Cayenne Hybrid",
  "Cayman",
  "Macan",
  "Panamera",
  "Panamera E-Hybrid",
  "Panamera E-Hybrid Sport Turismo",
  "Panamera Hybrid",
  "Panamera Sport Turismo",
  "S90",
  "Taycan",
  "Taycan Cross Turismo"
];

// Makes of RAM
const ramModels = [
  "All models",
  "1500",
  "1500 Classic",
  "2500",
  "3500",
  "Cargo",
  "ProMaster 1500",
  "ProMaster 2500",
  "ProMaster 2500 Window Van",
  "ProMaster 3500",
  "ProMaster 3500 Window Van",
  "ProMaster City"
];

// Makes of Subaru 
const subaruModels = [
  "All models",
  "1600",
  "1800",
  "Ascent",
  "B9 Tribeca",
  "Baja",
  "BRZ",
  "Crosstrek",
  "Crosstrek Hybrid",
  "Forester",
  "Impreza",
  "Impreza Outback Sport",
  "Impreza WRX",
  "Impreza WRX STi",
  "Legacy",
  "Outback",
  "Solterra",
  "STI S209",
  "Tribeca",
  "WRX",
  "WRX STI",
  "XV Crosstrek",
  "XV Crosstrek Hybrid"
];

// Makes of Tesla 
const teslaModels = [
  "All models",
  "Cybertruck",
  "Model 3",
  "Model S",
  "Model X",
  "Model Y",
  "Roadster"
];

// Models of Toyota 
const toyotaModels = [
  "All models",
  "4Runner",
  "86",
  "Avalon",
  "Avalon Hybrid",
  "bZ4X",
  "C-HR",
  "Camry",
  "Camry Hybrid",
  "Camry Solara",
  "Celica",
  "Corolla",
  "Corolla Cross",
  "Corolla Cross Hybrid",
  "Corolla Hatchback",
  "Corolla Hybrid",
  "Corolla iM",
  "Corona",
  "Cressida",
  "Crown",
  "ECHO",
  "FJ Cruiser",
  "GR Corolla",
  "GR Supra",
  "GR86",
  "Grand Highlander",
  "Grand Highlander Hybrid",
  "Highlander",
  "Highlander Hybrid",
  "Land Cruiser",
  "Matrix",
  "Mirai",
  "MR2",
  "Pickup Truck",
  "Previa",
  "Prius",
  "Prius c",
  "Prius Plug-in",
  "Prius Prime",
  "Prius v",
  "RAV4",
  "RAV4 EV",
  "RAV4 Hybrid",
  "RAV4 Prime",
  "Sequoia",
  "Sienna",
  "Supra",
  "T100",
  "Tacoma",
  "Tercel",
  "Tundra",
  "Tundra Hybrid",
  "Van",
  "Venza",
  "Yaris",
  "Yaris iA",
  "Yaris Sedan"
];

// Makes of Volkswagen
const volkswagenModels = [
  "All models",
  "1600",
  "Arteon",
  "Atlas",
  "Atlas Cross Sport",
  "Beetle",
  "Beetle (Pre-1980)",
  "Cabrio",
  "Cabriolet",
  "CC",
  "Corrado",
  "e-Golf",
  "Eos",
  "Eurovan",
  "GLI",
  "Golf",
  "Golf Alltrack",
  "Golf GTI",
  "Golf R",
  "Golf SportWagen",
  "GTI",
  "ID.4",
  "Jetta",
  "Jetta GLI",
  "Jetta Hybrid",
  "Jetta SportWagen",
  "Karmann Ghia",
  "Microbus",
  "New Beetle",
  "Passat",
  "Phaeton",
  "R32",
  "Rabbit",
  "Routan",
  "Super Beetle",
  "Taos",
  "Thing",
  "Tiguan",
  "Tiguan Limited",
  "Touareg",
  "Touareg 2",
  "Touareg Hybrid",
  "Van",
  "Vanagon"
];

// Makes of Volvo
const volvoModels = [
  "All models",
  "164",
  "1800",
  "240",
  "740",
  "760",
  "850",
  "940",
  "960",
  "C30",
  "C40 Recharge Pure Electric",
  "C70",
  "Coupe",
  "S40",
  "S60",
  "S60 Cross Country",
  "S60 Hybrid",
  "S60 Inscription",
  "S60 Recharge Plug-In Hybrid",
  "S70",
  "S80",
  "S90",
  "S90 Recharge Plug-In Hybrid",
  "V40",
  "V50",
  "V60",
  "V60 Cross Country",
  "V60 Recharge Plug-In Hybrid",
  "V70",
  "V90",
  "V90 Cross Country",
  "XC40",
  "XC40 Recharge Pure Electric",
  "XC60",
  "XC60 Recharge Plug-In Hybrid",
  "XC70",
  "XC90",
  "XC90 Hybrid",
  "XC90 Recharge Plug-In Hybrid"
];

  
  return (
    <div>
      <h1>Vehicle Search</h1>
      {/* Dropdown for make */}
      <div>
        <label>Make:</label>
        <select value={make} onChange={(e) => setMake(e.target.value)}>
          {/* Generate options for make */}
          {allMakes.map((make, index) => (
            <option key={index} value={make}>{make}</option>
          ))}
        </select>
      </div>
      {/* Dropdown for model */}
      <div>
        <label>Model:</label>
        <select value={model} onChange={(e) => setModel(e.target.value)}>
          {/* Generate options for model based on selected make */}
          {make === "Acura" && acuraModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
          {make === "Audi" && audiModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
          {make === "BMW" && bmwModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
          {make === "Buick" && buickModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
          {make === "Cadillac" && cadillacModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "Chevrolet" && chevroletModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "Chrysler" && chryslerModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
          {make === "Dodge" && dodgeModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "Ford" && fordModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "Genesis" && genesisModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "GMC" && gmcModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "Honda" && hondaModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "Hyundai" && hyundaiModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "INFINITI" && infinitiModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "Jaguar" && jaguarModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "Jeep" && jeepModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
           {make === "Kia" && kiaModels.map((model, index) => (
            <option key={index} value={model}>{model}</option>
          ))}
          {make === "Land Rover" && landRoverModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
          {make === "Lexus" && lexusModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
          {make === "Lincoln" && lincolnModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
          {make === "Mazda" && mazdaModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
          {make === "Mercedes-Benz" && mercedesModels.map((model, index) => (
          <option key={index} value={model}>{model}</option>
          ))}
          {make === "MINI" && miniModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
          {make === "Mitsubishi" && mitsubishiModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
          {make === "Nissan" && nissanModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
           {make === "Porsche" && porscheModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
           {make === "RAM" && ramModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
          {make === "Subaru" && subaruModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
           {make === "Tesla" && teslaModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
           {make === "Toyota" && toyotaModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
            {make === "Volkswagen" && volkswagenModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}
           {make === "Volvo" && volvoModels.map((model, index) => (
           <option key={index} value={model}>{model}</option>
          ))}


          {/* Add other makes' models here... */}
        </select>
      </div>
       {/* Dropdown for distance */}
       <div>
        <label>Distance:</label>
        <select value={distance} onChange={(e) => setDistance(e.target.value)}>
          <option value="">Select Distance</option>
          <option value="10">10 miles</option>
          <option value="20">20 miles</option>
          <option value="30">30 miles</option>
          <option value="40">40 miles</option>
          <option value="50">50 miles</option>
          <option value="75">75 miles</option>
          <option value="100">100 miles</option>
          <option value="150">150 miles</option>
          <option value="200">200 miles</option>
          <option value="250">250 miles</option>
          <option value="500">500 miles</option>
          <option value="">All miles from</option>
        </select>
      </div>
       {/* Input box for zip code */}
       <div>
        <label>Zip Code:</label>
        <input
          type="text"
          value={zipCode}
          onChange={(e) => setZipCode(e.target.value)}
          placeholder="Enter your zip code"
        />
      </div>
      {/* Button to trigger search */}
      <button onClick={handleSearch}>Search</button>
      {/* List of vehicles */}
      <ul>
        {vehicles.map(vehicle => (
          <li key={vehicle.id}>
            <h2>{vehicle.make} {vehicle.model}</h2>
            <p>Year: {vehicle.year}</p>
            {/* Add additional vehicle details as needed */}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;